### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by sandipndev** [kyoz/mac-arch#1]

**Comment by spantheslayer** [comment]
because your dad asked for it

**Comment by kyoz** [comment]
Hello @sandipndev, everyone love macbook design and duriability, but base on different works and hobbies, sometime we need to work on different system (Coding enviroment, testing...etc).

Of course if you don't know what linux is and what it for, the integrated unix system of Macbook is good enough. But when you deep dive in linux world, you'll find out that it has a lots of thing that OSX doesn't have (speed, opensource, window management...etc).

And this installation guide help we dual boot, not just install arch only, We can still use OSX whatever we want.

Hope this help you understand why this exist.
